config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # organization関連==================================================
  resources :organizations do
    scope module: :organizations do
      resources :folders
      resources :videos, only: [:index]
    end
    member do
      scope module: :organizations do
        resource :unsubscribe, only: %i[show update], as: :organizations_unsubscribe
        resource :admission, only: %i[show update destroy], as: :organizations_admission
        resource :payment, only: %i[new create], as: :organizations_payment
      end
    end
  end

  # =================================================================

  # system_admin関連=========================================================
  devise_for :system_admins, skip: %i[registrations], controllers: {
    sessions:  'system_admins/sessions',
    passwords: 'system_admins/passwords'
  }

  resources :system_admins, only: %i[show edit update] do
  end
  # =================================================================

  # user関連=======================================================
  devise_for :users, skip: %i[registrations], controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  resources :users do
    member do
      scope module: :users do
        resource :unsubscribe, only: %i[show update], as: :users_unsubscribe
      end
    end
  end

  post 'users_create', to: 'users#create'
  # =================================================================

  # viewer関連==========================================================
  devise_for :viewers, controllers: {
    sessions:      'viewers/sessions',
    passwords:     'viewers/passwords',
    confirmations: 'viewers/confirmations',
    registrations: 'viewers/registrations'
  }

  resources :viewers do
    member do
      scope module: :viewers do
        resource :unsubscribe, only: %i[show update], as: :viewers_unsubscribe
      end
    end
  end

  resources :groups, param: :uuid
  # =================================================================

  # video関連=========================================================
  resources :videos do
    member do
      get 'popup_before'
      get 'popup_after'
    end

    resources :comments, only: %i[create update destroy] do
      resources :replies, only: %i[create update destroy]
    end
  end

  # =================================================================

   
  # aws_s3 関連=======================================================
  resources :aws_s3 do
    get 'popup_before', to:'aws_s3#popup_before'
    get 'popup_after', to:'aws_s3#popup_after'
    resources :comments, only: %i[create update destroy] do
      resources :replies, only: %i[create update destroy]
    end
  end

  # =============================================================




  # 共通==============================================================
  # トップページ
  root 'use#top'
  # 利用規約
  get 'use/terms' => 'use#terms', as: 'use_terms'
  # プライバシーポリシー
  get 'use/privacy_policy' => 'use#privacy_policy', as: 'use_privacy_policy'
  # =================================================================

  resources :videos do
    scope module: :videos do
      resources :video_folders, only: :destroy
      # 動画検索機能
      collection do
        get 'videos/search' => 'searches#search'
      end
    end
    collection do
      scope module: :videos do
        resource :recording, only: :new
      end
    end
  end

  # 動画の論理削除(データは残すが表示しないという意味でhiddensコントローラと命名)
  scope module: :videos do
    get 'videos/:id/hidden' => 'hiddens#confirm', as: :videos_hidden
    patch 'videos/:id/withdraw' => 'hiddens#withdraw', as: :videos_withdraw
  end

  # 決済機能webhook関連
  post 'webhooks' => 'webhooks#create'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :organization
  has_many :viewer_groups
  has_many :group_videos
  has_many :videos, through: :group_videos
  has_many :viewers, through: :viewer_groups, dependent: :destroy

  before_create -> { self.uuid = SecureRandom.uuid }
  validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout 'groups', only: %i[index show new edit update create destroy remove_viewer]
  before_action :ensure_logged_in
  before_action :ensure_admin_or_user
  before_action :set_group, only: %i[show edit update destroy remove_viewer]
  before_action :check_viewer, only: %i[show edit update destroy remove_viewer]
  before_action :check_permission, only: [:destroy]

  def index
    if current_user
      @groups = Group.where(organization_id: current_user.organization_id)
      @select_organization = current_user.organization
    elsif current_system_admin
      @groups = Group.where(organization_id: params[:organization_id])
      @select_organization = Organization.find(params[:organization_id]) if params[:organization_id].present?
    end
  end

  def show; end

  def new
    @group = Group.new
    organization_id = params[:organization_id] || current_user.organization_id
    @viewers = Viewer.for_current_user(current_user, organization_id)
  end

  def create
    @group = Group.new(group_params)
    @group.organization_id = current_user.organization_id
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
    organization_id = params[:organization_id] || current_user&.organization_id
    if organization_id.nil?
      flash[:error] = '組織IDが見つかりません'
      redirect_back(fallback_location: root_path) and return
    end

    if current_system_admin?
      @viewers = Viewer.for_system_admin(organization_id)
    else
      @viewers = Viewer.for_current_user(current_user, organization_id)
    end
  end

  def update
    if @group.update(group_params)
      flash[:success] = '視聴グループを編集しました。'
      redirect_to groups_path(organization_id: @group.organization_id)
    else
      flash[:danger] = '視聴グループ名を入力してください'
      redirect_to edit_group_path(@group.uuid, organization_id: @group.organization_id)
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, notice: 'グループを削除しました。'
  end

  def remove_viewer
    viewer = Viewer.find(params[:viewer_id])
    @group.viewers.delete(viewer)
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, viewer_ids: [])
  end

  def set_group
    @group = Group.find_by(uuid: params[:uuid])
  end

  def check_viewer
    if !current_system_admin? && @group.organization_id != current_user.organization_id
      flash[:danger] = '権限がありません。'
      redirect_back(fallback_location: root_url)
    end
  end

  def check_permission
    unless current_user&.role == 'owner' || current_system_admin?
      flash[:danger] = '権限がありません。'
      redirect_back(fallback_location: root_url)
    end
  end
end

app/views/groups/_form.html.erb
<head>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
  <!-- validateプラグインの読み込み -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<!-- 対象グループ情報 -->
<%= render '/shared/error_messages', object: f.object %>
<%= f.label :name %>
<%= f.text_field :name, id: 'group_name', class: "form-control" %><br>
<%= f.label :viewer %>
<%= f.collection_select :viewer_ids, @viewers || [], :id, :name, {}, { class: 'form-control select2', id: 'viewer-select', multiple: true, style: "width: 100%" } %>

<script>
  $(document).ready(function(){
    let isInitialized = false;
    function initializeSelect2() { // 要素が表示されるまで待つ
      $('#viewer-select').select2({
        width: 'resolve',
        theme: 'classic',
        multiple: 'multiple',
        allowClear: true
      });
      isInitialized = true;
    }

    let checkExist = setInterval(function() {
      if ($('#viewer-select').length && !isInitialized) {
        clearInterval(checkExist);
        initializeSelect2();
      }
    }, 100); // 100 ミリ秒ごとにチェックする
  });
</script>

app/views/groups/edit.html.erb
<% provide(:title, "視聴グループ編集") %>
<% provide(:btn_text, "更新") %>

<div class="card">
  <%= form_with model: @group, url:group_path(@group.uuid), local: true do |f| %>
    <div class="card-body">
      <%= render partial: "form", locals: { f: f, group: @group } %>
    </div>
    <div class="card-footer">
      <%= f.submit yield(:btn_text), class: "btn btn-md btn-block btn-success" %><br>
      <%= link_to "一覧画面へ", groups_path(organization_id: @group.organization_id), class: "btn btn-md btn-block btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<% provide(:title, "視聴グループ一覧") %>
<% if current_user.present? %>
<%= link_to "視聴グループ　新規作成画面へ", new_group_path, class: "btn btn-lg btn-block btn-outline-primary" %>
<% end %><br><br>

<% if @groups.count == 0 && current_system_admin %>
  <div class="center-message">
    <h2>視聴グループはまだ作成されていません。</h2>
  </div>
<% end %>

<% if @groups.count != 0 %>
  <div class="card">
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-nowrap"> 
        <thead>
          <tr align="center">
            <th>視聴グループ名</th>
            <th><%= @select_organization.name %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr align="center">
              <td><%= link_to group.name, group_path(group.uuid) %></td>
              <td><%= link_to "編集", edit_group_path(group.uuid, organization_id: group.organization_id), class: "btn btn-success" %></td>
              <td><%= link_to "削除", group_path(group.uuid), method: :delete, data: { confirm: "#{group.name}の視聴者グループを削除します。本当によろしいですか？" }, class: "btn btn-md btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/groups/new.html.erb
<% provide(:title, "視聴グループ登録") %>
<% provide(:btn_text, "登録") %>

<div class="card">
  <%= form_with model: @group, url: groups_path, html: { method: :post }, local: true do |f| %>
    <div class="card-body">
      <%= render partial: "form", locals: { f: f } %>
    </div>
    <div class="card-footer">
      <%= f.submit yield(:btn_text), class: "btn btn-md btn-block btn-success" %><br>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<% provide(:title, "視聴グループ詳細") %>

<div class="card">
  <div class="card-body table-responsive p-0">
    <table class="table table-hover text-nowrap">
      <tbody>
        <tr>
          <th><%= Group.human_attribute_name(:name) %></th>
          <td><%= @group.name %></td>
        </tr>
        <tr>
          <th><%= Group.human_attribute_name(:viewer) %></th>
          <td><%= Viewer.where(id: @group.viewer_ids).pluck(:name).join(', ') %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= link_to "編集", edit_group_path(@group.uuid, organization_id: @group.organization_id), class: "btn btn-md btn-block btn-success" %>
    <%= link_to "削除", group_path(@group.uuid), method: :delete, data: { confirm: "#{@group.name}の視聴グループを削除します。本当によろしいですか？" }, class: "btn btn-md btn-block btn-danger" %></br>
    <%= link_to "一覧画面へ", groups_path, class: "btn btn-md btn-block btn-secondary" %>
  </div>
</div>