config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # organization関連==================================================
  resources :organizations do
    scope module: :organizations do
      resources :folders
      resources :videos, only: [:index]
    end
    member do
      scope module: :organizations do
        resource :unsubscribe, only: %i[show update], as: :organizations_unsubscribe
        resource :admission, only: %i[show update destroy], as: :organizations_admission
        resource :payment, only: %i[new create], as: :organizations_payment
      end
    end
  end

  # =================================================================

  # system_admin関連=========================================================
  devise_for :system_admins, skip: %i[registrations], controllers: {
    sessions:  'system_admins/sessions',
    passwords: 'system_admins/passwords'
  }

  resources :system_admins, only: %i[show edit update] do
  end
  # =================================================================

  # user関連=======================================================
  devise_for :users, skip: %i[registrations], controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  resources :users do
    member do
      scope module: :users do
        resource :unsubscribe, only: %i[show update], as: :users_unsubscribe
      end
    end
  end

  post 'users_create', to: 'users#create'
  # =================================================================

  # viewer関連==========================================================
  devise_for :viewers, controllers: {
    sessions:      'viewers/sessions',
    passwords:     'viewers/passwords',
    confirmations: 'viewers/confirmations',
    registrations: 'viewers/registrations'
  }

  resources :viewers do
    member do
      scope module: :viewers do
        resource :unsubscribe, only: %i[show update], as: :viewers_unsubscribe
      end
    end
  end

  resources :groups, param: :uuid
  # =================================================================

  # video関連=========================================================
  resources :videos do
    member do
      get 'popup_before'
      get 'popup_after'
    end

    resources :comments, only: %i[create update destroy] do
      resources :replies, only: %i[create update destroy]
    end
  end

  # =================================================================

   
  # aws_s3 関連=======================================================
  resources :aws_s3 do
    get 'popup_before', to:'aws_s3#popup_before'
    get 'popup_after', to:'aws_s3#popup_after'
    resources :comments, only: %i[create update destroy] do
      resources :replies, only: %i[create update destroy]
    end
  end

  # =============================================================




  # 共通==============================================================
  # トップページ
  root 'use#top'
  # 利用規約
  get 'use/terms' => 'use#terms', as: 'use_terms'
  # プライバシーポリシー
  get 'use/privacy_policy' => 'use#privacy_policy', as: 'use_privacy_policy'
  # =================================================================

  resources :videos do
    scope module: :videos do
      resources :video_folders, only: :destroy
      # 動画検索機能
      collection do
        get 'videos/search' => 'searches#search'
      end
    end
    collection do
      scope module: :videos do
        resource :recording, only: :new
      end
    end
  end

  # 動画の論理削除(データは残すが表示しないという意味でhiddensコントローラと命名)
  scope module: :videos do
    get 'videos/:id/hidden' => 'hiddens#confirm', as: :videos_hidden
    patch 'videos/:id/withdraw' => 'hiddens#withdraw', as: :videos_withdraw
  end

  # 決済機能webhook関連
  post 'webhooks' => 'webhooks#create'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :organization
  belongs_to :user
  has_many :group_videos
  has_many :groups, through: :group_videos

  has_one_attached :video
  has_many :comments, dependent: :destroy

  has_many :video_folders, dependent: :destroy
  has_many :folders, through: :video_folders

  validates :title, presence: true
  validates :title, uniqueness: { scope: :organization }, if: :video_exists?
  validates :video, presence: true, blob: { content_type: :video }

  def video_exists?
    video = Video.where(title: self.title, is_valid: true).where.not(id: self.id)
    video.present?
  end

  scope :user_has, ->(organization_id) { where(organization_id: organization_id) }
  scope :current_user_has, ->(current_user) { where(organization_id: current_user.organization_id) }
  scope :current_viewer_has, ->(organization_id) { where(organization_id: organization_id) }
  scope :available, -> { where(is_valid: true) }

  def identify_organization_and_user(current_user)
    self.organization_id = current_user.organization.id
    self.user_id = current_user.id
  end

  def user_no_available?(current_user)
    self.organization_id != current_user.organization_id
  end

  def my_upload?(current_user)
    return true if self.user_id == current_user.id

    false
  end

  def ensure_owner?(current_user)
    return true if current_user.role == 'owner'

    false
  end

  # ビデオ検索機能
  scope :search, lambda { |search_params|
    # 検索フォームが空であれば何もしない
    return if search_params.blank?

    # ひらがな・カタカナは区別しない
    title_like(search_params[:title_like])
      .open_period_from(search_params[:open_period_from])
      .open_period_to(search_params[:open_period_to])
      .range(search_params[:range])
      .user_like(search_params[:user_name])
  }

  scope :title_like, ->(title) { where('title LIKE ?', "%#{title}%") if title.present? }
  # DBには世界時間で検索されるため9時間マイナスする必要がある
  scope :open_period_from, ->(from) { where('? <= open_period', DateTime.parse(from) - 9.hours) if from.present? }
  scope :open_period_to, ->(to) { where('open_period <= ?', DateTime.parse(to) - 9.hours) if to.present? }
  scope :range, lambda { |range|
    if range.present?
      if range == 'all'
        nil
      else
        where(range: range)
      end
    end
  }
  scope :user_like, ->(user_name) { joins(:user).where('users.name LIKE ?', "%#{user_name}%") if user_name.present? }
end

app/controllers/videos/hiddens_controller.rb
class Videos::HiddensController < VideosController
  before_action :ensure_logged_in
  before_action :set_video
  before_action :ensure_admin_or_user
  before_action :ensure_admin_or_owner
  before_action :ensure_my_organization

  def confirm; end

  def withdraw
    if @video.update(is_valid: false)
      flash[:success] = '削除しました'
      redirect_to videos_url(organization_id: @video.organization.id)
    else
      render :show
    end
  end

  private

  # 共通メソッド(organization::foldersコントローラにも記載)
  def ensure_admin_or_owner
    if current_user.present? && current_user.role != 'owner'
      redirect_to users_url, flash: { danger: '権限がありません' }
    end
  end
end

app/controllers/videos/notices_controller.rb
class Videos::NoticesController < VideosController
  before_action :ensure_set_video_expire
  skip_before_action :ensure_logged_in

  def expire; end

  private

  def ensure_set_video_expire
    redirect_to root_url if !Video.find(params[:id]).open_period || (Video.find(params[:id]).open_period&.>Time.current)
  end
end

app/controllers/videos/recordings_controller.rb
class Videos::RecordingsController < ApplicationController
  before_action :ensure_current_user
  layout 'recordings'

  private

  # ログイン中のuserのみ許可
  def ensure_current_user
    unless current_user?
      flash[:danger] = '権限がありません。'
      redirect_back(fallback_location: root_url)
    end
  end
end

app/controllers/videos/searches_controller.rb
class Videos::SearchesController < VideosController
  def search
    @search_params = video_search_params
    if current_system_admin.present?
      @organization_videos = Video.includes([:video_blob]).user_has(session[:organization_id]).search(@search_params)
    elsif current_user.present?
      @organization_videos = Video.includes([:video_blob]).current_user_has(current_user).available.search(@search_params)
    elsif current_viewer.present?
      @organization_videos = Video.includes([:video_blob]).current_viewer_has(session[:organization_id]).available.search(@search_params)
    end
    render :index
  end

  private

  def video_search_params
    params.fetch(:search, {}).permit(:title_like, :open_period_from, :open_period_to, :range, :user_name)
  end
end

app/controllers/videos/video_folders_controller.rb
class Videos::VideoFoldersController < VideosController
  before_action :ensure_admin_or_owner_or_correct_user
  before_action :ensure_my_organization
  skip_before_action :ensure_admin

  def destroy
    folder = Folder.find(params[:folder_id])
    video_folder = folder.video_folders.find_by(video_id: params[:video_id])
    video_folder.destroy
    redirect_to organization_folder_url(folder, organization_id: params[:organization_id]), flash: { danger: '動画をフォルダ内から削除しました' }
  end

  private

  def set_video
    Video.find(params[:video_id])
  end

  def ensure_admin_or_owner_or_correct_user
    # videosコントローラのメソッドと、メソッド名は同じ、処理内容はオーバーライド
    video = set_video
    unless current_system_admin.present? || video.user_id == current_user.id || current_user.role == 'owner'
      redirect_to organization_folders_url(params[:organization_id]), flash: { danger: '権限がありません。' }
    end
  end

  def ensure_my_organization
    # videosコントローラのメソッドと、メソッド名は同じ、処理内容はオーバーライド
    if current_user.present?
      video = set_video
      unless current_user.organization_id == video.organization_id
        redirect_to organization_folders_url(params[:organization_id]), flash: { danger: '権限がありません。' }
      end
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include CommentReply
  helper_method :account_logged_in?
  before_action :ensure_logged_in, except: :show
  before_action :set_organization, only: %i[index]
  before_action :set_video, only: %i[show edit update destroy]
  before_action :ensure_admin_or_user, only: %i[new create edit update destroy]
  before_action :ensure_user, only: %i[new create]
  before_action :ensure_admin_or_owner_or_correct_user, only: %i[update]
  before_action :ensure_my_organization, exept: %i[new create]
  # 視聴者がログインしている場合、表示されているビデオの視聴グループ＝現在の視聴者の視聴グループでなければ、締め出す下記のメソッド追加予定
  # before_action :limited_viewer, only: %i[show]
  before_action :ensure_logged_in_viewer, only: %i[show]
  before_action :ensure_admin_for_access_hidden, only: %i[show edit update]

  def index
    # 動画検索機能用に記載
    @search_params = video_search_params
    if current_system_admin.present?
      # 動画検索機能用に記載 リセットボタン、検索ボタン押下後paramsにorganization_idが含まれないためsessionに保存
      session[:organization_id] = params[:organization_id]
      @organization_videos = Video.includes([:video_blob]).user_has(params[:organization_id])
    elsif current_user.present?
      @organization_videos = Video.includes([:video_blob]).current_user_has(current_user).available
    elsif current_viewer.present?
      # 動画検索機能用に記載 リセットボタン、検索ボタン押下後paramsにorganization_idが含まれないためsessionに保存
      session[:organization_id] = params[:organization_id]
      @organization_videos = Video.includes([:video_blob]).current_viewer_has(params[:organization_id]).available
      # 現在の視聴者の視聴グループに紐づくビデオのみを表示するよう修正が必要(第２フェーズ)
    end
  end

  def new
    @video = Video.new
    @video.video_folders.build
    @groups = current_user_with_org_and_groups.organization.groups
  end

  def create
    @video = Video.new(video_params)
    @video.identify_organization_and_user(current_user)
    @video.groups = Group.where(id: params[:video][:group]) if params[:video][:group]
    if @video.save
      flash[:success] = '動画を投稿しました。'
      redirect_to @video
    else
      @groups = current_user.organization.groups if current_user.present?
      render :new
    end
  rescue StandardError => e
    logger.error e.message
    @groups = current_user.organization.groups if current_user.present?
    render :new
  end

  def show
    set_account
    @comment = Comment.new
    @reply = Reply.new
    # 新着順で表示
    @comments = @video.comments.includes(:system_admin, :user, :viewer, :replies).order(created_at: :desc)
  end

  def edit; end

  def update
    if @video.update(video_params)
      flash[:success] = '動画情報を更新しました'
      redirect_to video_url
    else
      render 'edit'
    end
  end

  def destroy
    @video.destroy
    flash[:success] = '削除しました'
    redirect_to videos_url(organization_id: @video.organization.id)
  end

  private

  def video_params
    params.require(:video).permit(:title, :video, :open_period, :range, :login_set, :popup_before_video,
      :popup_after_video, { folder_ids: [] })
  end

  def video_search_params
    params.fetch(:search, {}).permit(:title_like, :open_period_from, :open_period_to, :range, :user_name)
  end

  # 共通メソッド(organization::foldersコントローラにも記載)
  def set_organization
    @organization = Organization.includes(:groups).find(params[:organization_id])
  end

  def ensure_user
    if current_user.nil?
      # 修正 遷移先はorganization::foldersコントローラのものとは異なる
      redirect_to root_url, flash: { danger: '権限がありません' }
    end
  end

  # videosコントローラ独自メソッド
  def set_video
    @video = Video.find(params[:id])
  end

  def ensure_admin_or_owner_or_correct_user
    unless current_system_admin.present? || @video.my_upload?(current_user) || current_user.role == 'owner'
      redirect_to video_url, flash: { danger: '権限がありません。' }
    end
  end

  def ensure_my_organization
    if current_user.present?
      # indexへのアクセス制限とshow, eidt, update, destroyへのアクセス制限
      if (@organization.present? && current_user.organization_id != @organization.id) ||
         (@video.present? && @video.user_no_available?(current_user))
        flash[:danger] = '権限がありません。'
        redirect_to videos_url(organization_id: current_user.organization_id)
      end
    elsif current_viewer.present?
      # indexへのアクセス制限とshowへのアクセス制限
      if (@organization.present? && current_viewer.organization_viewers.where(organization_id: @organization.id).empty?) ||
         (@video.present? && current_viewer.organization_viewers.where(organization_id: @video.organization_id).empty?)
        flash[:danger] = '権限がありません'
        redirect_back(fallback_location: root_url)
      end
    end
  end

  def ensure_logged_in_viewer
    if !logged_in? && @video.login_set != false
      redirect_to new_viewer_session_url, flash: { danger: '視聴者ログインしてください。' }
    end
  end

  def ensure_admin_for_access_hidden
    if current_system_admin.nil? && @video.is_valid == false
      flash[:danger] = 'すでに削除された動画です。'
      redirect_back(fallback_location: root_url)
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
  def selected_before_range
    return ['限定公開', 1] if @video.range
  end

  def selected_before_comment_public
    return ['非公開', 1] if @video.comment_public
  end

  def selected_before_login_set
    return ['ログイン必要', 1] if @video.login_set
  end

  def selected_before_popup_before_video
    return ['動画視聴開始時ポップアップ非表示', 1] if @video.popup_before_video
  end

  def selected_before_popup_after_video
    return ['動画視聴終了時ポップアップ非表示', 1] if @video.popup_after_video
  end
end

app/views/videos/_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">動画情報設定</h1>
    </div>
    <div class="modal-body">
      <div class="content">
        <%= form_with(model: @video, url:video_path(@video), local:false ) do |f| %>
          <%= render '/shared/error_messages', object: f.object %>
          <div class="field">
            <%= f.label :title, class: "video-label" %><br>
            <%= f.text_field :title, id: "title_edit" %><br>
          </div>
          <div class="field">
            <%= f.label :open_period, class: "video-label" %><br>
            <%= f.datetime_field :open_period , id:"open_period_edit" %> 
          </div>
          <div class="field">
            <%= f.label :range, class: "video-label" %><br>   
            <%= f.select :range, [['一般公開',0],['限定公開',1]], { include_blank: false, selected: selected_before_range }, id:"range_edit" %>  
          </div> 
       
          <div class="field">
            <%= f.label :comment_public, class: "video-label" %><br>
            <%= f.select :comment_public, [['公開',0],['非公開',1]], { include_blank: false, selected: selected_before_comment_public },  id:"comment_public_edit" %>
          </div> 
          <div class= "field">
            <%= f.label :login_set, class: "video-label" %><br>     
            <%= f.select :login_set, [['ログイン不要',0],['ログイン必要',1]], { include_blank: false, selected: selected_before_login_set }, id:"login_set_edit" %> 
          </div>
          <div class="field">
            <%= f.label :popup_before_video, class: "video-label" %><br>
            <%= f.select :popup_before_video, [['動画視聴開始時ポップアップ表示',0],['動画視聴開始時ポップアップ非表示',1]], { include_blank: false, selected: selected_before_popup_before_video }, id:"popup_before_video_edit" %>
          </div> 
          <div class="field">
            <%= f.label :popup_after_video, class: "video-label" %><br>
            <%= f.select :popup_after_video, [['動画視聴終了時ポップアップ表示',0],['動画視聴終了時ポップアップ非表示',1]], { include_blank: false, selected: selected_before_popup_after_video }, id:"popup_after_video_edit" %>
          </div>

          <%= f.label :folders, class: "video-label" %><br>
          <% if current_system_admin.present? %>
            <%= collection_check_boxes(:video, :folder_ids, Folder.assigned_by_the_video_setting(@video), :id, :name) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %><br>
          <% else %>
            <%= collection_check_boxes(:video, :folder_ids, Folder.current_user_has(current_user), :id, :name) do |b| %>
              <%= b.label { b.check_box + b.text } %>
            <% end %><br>
          <% end %>
            
          <div class="video-post-actions">   
            <% if system_admin_signed_in? || @video.my_upload?(current_user) || @video.ensure_owner?(current_user) %> 
              <%= f.submit "設定を変更", class: "btn btn-primary" %>   
            <% end %>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/videos/_popup_after.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">popup_after</h1>
    </div>
    <div class="modal-body">
      <div class="content">
      </div>
    </div>
  </div>
</div>

app/views/videos/_popup_before.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title">popup_before</h1>
      <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="modal"></button>

    </div>
    <div class="modal-body">
      <div class="content">
      </div>
    </div>
  </div>
</div>

app/views/videos/cut_video.html.erb
<h3>動画編集ページ</h3><br>
<div>
<h5>動画切り抜き</h5>
<%= form_with(url: { action: 'cut_video_edit' }, method: :post, local: false, multipart: true) do |form| %>
  
  <%= form.label :new_title, '新しいタイトル:' %>
  <%= form.text_field :new_title, placeholder: '例: タイトルを記入してください' %><br>
  
  <%= form.label :start_time, '開始時間（秒）:' %>
  <%= form.text_field :start_time, placeholder: '例: 10' %><br>

  <%= form.label :duration, '切り抜く時間（秒）:' %>
  <%= form.text_field :duration, placeholder: '例: 5' %><br>

  <%= form.label :video_file, '動画ファイルを選択:' %>
  <%= form.file_field :video_file %><br>

  <%= form.submit '動画を切り抜く', class:"btn btn-success" %>
<% end %> <br>
</div>

<div>
<h5>音声データ作成</h5>
<%= form_with(url: { action: 'audio_output' }, method: :post, local: false, multipart: true) do |form| %>

  <%= form.label :subtitle_file, "字幕を付与するファイルを選択："%>
  <%= form.file_field :subtitle%><br>

  <%= form.submit '字幕付きデータ作成', class:"btn btn-success" %>
<% end %>
</div>

app/views/videos/edit.js.erb
$("#edit").html("<%= escape_javascript(render 'edit') %>");
$("#edit").modal("show");

app/views/videos/index.html.erb
<% provide(:title, "ビデオ一覧") %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<div class="content">
  <div class="col-md-10 offset-1">
    <div class="video-search-form">
      <%= render partial: 'videos/searches/search_form' %>
    </div>
    <div class="video-search-result">
      <!-- リセットボタン押下であれば検索結果メッセージは表示しない -->
      <% if params[:video_form_reset] %>
      <% elsif @search_params.present? && @organization_videos.count != 0 %>
        <%= @organization_videos.count %>件ヒットしました。
      <% elsif @search_params.present? %>
        該当する動画はありませんでした。
      <% end %>
    </div>  
    <% @organization_videos.each do |organization_video| %>
      <div style="float:left;margin:15px;">
        <div class="video-display-index">
          <% if organization_video.video.attached? %>
            <video width="200" height="100" controls>
              <source src="<%= url_for(organization_video.video) %>" type="<%= organization_video.video.content_type %>">
              お使いのブラウザは動画再生に対応していません。
            </video>
          <% else %>
            <p>動画がありません</p>
          <% end %>
        </div>
        <div class="video-title-and-action-index">
          <%= link_to organization_video.title, video_path(organization_video) %>
          <% if organization_video.is_valid == false %>
            <span>オーナー削除済み</span>
          <% end %><br>
          <% if current_system_admin or current_user.present? %>   
            <%= link_to "削除", video_path(organization_video), method: :delete, data:{confirm: "削除しますか？"}, class: "btn btn-danger mt-2" %><br>
          <% end %>  
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<% provide(:title,  "ビデオ投稿") %>
<div class="content">
  <%= form_with(model: @video, url:videos_path, local:true ) do |f| %>
    <%= render '/shared/error_messages', object: f.object %>
    <div class="row">
      <div class="col-md-7">
        <div class="field">
          <%= f.label :video %><br>
          <%= f.file_field :video, accept: "video/*", id:"post" %> 
        </div>
        <!--このclassのエリアを、file_fieldの上に被せる-->
        <div class="choice_box">ドラック＆ドロップまたはクリック</div><br>
        <!--ここにプレビュー表示-->
        <div id="show"></div>
      </div>
      <div class="col-md-5 video-info">
        <div class="field">
          <%= f.label :title, class: "video-label" %><br>
          <%= f.text_field :title, id: "title" %><br>
        </div>
        <div class="field">
          <%= f.label :open_period, class: "video-label" %><br>
          <%= f.datetime_field :open_period , id:"open_period" %> 
        </div>
        <div class="field">
          <%= f.label :range, class: "video-label" %><br>
          <%= f.select :range, [['一般公開',0],['限定公開',1]], { include_blank: false, selected: 0 }, id:"range" %>
        </div> 
        <div class="field">
          <%= f.label :comment_public, class: "video-label" %><br>
          <%= f.select :comment_public, [['公開',0],['非公開',1]], { include_blank: false, selected: 0 }, id:"comment_public" %>
        </div>
        <div class="field">
          <%= f.label :login_set, class: "video-label" %><br>
          <%= f.select :login_set, [['ログイン不要',0],['ログイン必要',1]], { include_blank: false, selected: 0 }, id:"login_set" %>
        </div>
        <div class="field">
          <%= f.label :popup_before_video, class: "video-label" %><br>
          <%= f.select :popup_before_video, [['動画視聴開始時ポップアップ表示',0],['動画視聴開始時ポップアップ非表示',1]], { include_blank: false, selected: 0 }, id:"popup_before_video" %>
        </div>
        <div class="field">
          <%= f.label :popup_after_video, class: "video-label" %><br>
          <%= f.select :popup_after_video, [['動画視聴終了時ポップアップ表示',0],['動画視聴終了時ポップアップ非表示',1]], { include_blank: false, selected: 0 }, id:"popup_after_video" %>
        </div>
        <div class="field">
          <%= f.label :folders, class: "video-label" %><br>
          <%= collection_check_boxes(:video, :folder_ids, Folder.current_user_has(current_user).includes([:organization]), :id, :name) do |b| %>
            <%= b.label { b.check_box + b.text } %>
          <% end %><br>
          <%= link_to "フォルダ新規作成はこちら", new_organization_folder_path(organization_id: current_user.organization.id), remote: true %>
        </div>
        <div class="video-post-actions">
          <%= f.submit "新規投稿", class: "btn btn-success"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/videos/popup_after.js.erb
$("#popup_after").html("<%= escape_javascript(render 'popup_after') %>");
$("#popup_after").modal("show");

app/views/videos/popup_before.js.erb
$("#popup_before").html("<%= escape_javascript(render 'popup_before') %>");
$("#popup_before").modal("show");

app/views/videos/show.html.erb
<% provide(:title, "ビデオ詳細") %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<% if @video.popup_before_video == true %>
  <%= link_to "popb", popup_before_video_path(@video), remote: true, id: "hiddenPopupBeforeLink", class: "btn", style: "display: none;" if user_signed_in? || system_admin_signed_in? %>
<% end %>
<% if @video.popup_after_video == true %>
  <%= link_to "popa", popup_after_video_path(@video), remote: true, id: "hiddenPopupAfterLink", style: "display: none;" if user_signed_in? || system_admin_signed_in? %>
<% end %>

<div class="content">
  <div class="video-display-show">
    <% if @video.video.attached? %>
      <video width="1000" height="500" id="mv" controls>
        <source src="<%= url_for(@video.video) %>" type="<%= @video.video.content_type %>">
        お使いのブラウザは動画再生に対応していません。
      </video><br>
    <% else %>
      <p>動画がありません</p>
    <% end %>
  </div>
  <div class="video-title-and-action-show">
    <%= @video.title %><br>
    <%= link_to "設定", edit_video_path(@video), remote: true, class: "btn btn-success" if user_signed_in? || system_admin_signed_in? %>
    <% if @video.is_valid == true %>
      <%= link_to "削除", videos_hidden_path(@video), class: "btn btn-danger" if system_admin_signed_in? || current_user.present? && current_user.role == "owner" %>
    <% else %>
      <p>オーナー削除済み</p>
    <% end %>
  </div>
</div>    

<!-- 動画コメント ------------------------------------------------------------------------>
<div class="container">
  <div class="row">
    <div class="col-8">
      <% if account_logged_in? %>
        <div class="comment-create">
          <h4 class="text-left">コメントを投稿する</h4>
          <%= render partial: 'comments/form' %>
        </div>
        <br>
      <% end %>   
      <hr>
        
      <!-- コメント表示・非表示ボタン -->
      <button id="toggle-comments-button" class="btn btn-secondary">コメントを表示する</button>

      <!-- コメントエリア -->
      <div id="comments_area" style="display: none;">
        <%= render partial: 'comments/index' if @comments.present? %>  
      </div>
    </div>  
  </div>
</div>
<!-- 動画コメント ------------------------------------------------------------------------>

<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="popup_before" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="popup_after" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/videos/video_edit.html.erb
<h1><%= @video.title%></h1>
<%= button_to 'ダウンロード',download_video_video_path(@video), method: :get, remote: true %>
</iframe>

<%= @video.data_url[8..17].to_i %>

<%= form_tag({ action: 'cut_video' }, method: :post) do
  <%# <label for="start_time">開始時間（秒）:</label>
  <%= text_field_tag 'start_time', nil, placeholder: '例: 10' %>

  <%# <label for="duration">切り抜く時間（秒）:</label>
  <%= text_field_tag 'duration', nil, placeholder: '例: 5' %>

  <%= submit_tag '動画を切り抜く'%>
 <% end %> 

<!-- ここに動画のプレビューを表示するための部分 -->
<% if params[:start_time].present? && params[:duration].present? %> %>
 <p>動画を以下の条件で切り抜きます：</p>
  <p>開始時間： <%= params[:start_time] %> 秒</p>
  <p>切り抜く時間： <%= params[:duration] %> 秒</p> 

  <!-- ここに動画のプレビューを表示するコードを追加 -->
<% end %> 